#!/bin/bash

IP=$(wget -qO- ipv4.icanhazip.com)

verif_ptrs() {
    porta=$1
    PT=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" | grep -v "COMMAND" | grep "LISTEN")
    for pton in $(echo -e "$PT" | cut -d: -f2 | cut -d' ' -f1 | uniq); do
        svcs=$(echo -e "$PT" | grep -w "$pton" | awk '{print $1}' | uniq)
        if [ "$porta" = "$pton" ]; then
            dialog --msgbox "PORTA $porta EM USO PELO $svcs" 7 40
            sleep 3
            fun_chuser
        fi
    done
}

uninstall_checkuser() {
    dialog --infobox "Desinstalando o Checkuser..." 5 40
    pkill -f atx.py
    rm -f /usr/lib/checkuser/atx.py
    rm -f /usr/bin/chuser
    rm -f /usr/bin/userscheck
    rm -f /root/instcheck.sh
    rmdir /usr/lib/checkuser
    dialog --msgbox "Checkuser desinstalado com sucesso." 7 40
    sleep 2
}

check_installed() {
    if [ -f "/usr/lib/chuser/atx.py" ]; then
        return 0  # Já instalado
    else
        return 1  # Não instalado
    fi
}

fun_bar() {
    comando[0]="$1"
    comando[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${comando[0]} >/dev/null 2>&1
        ${comando[1]} >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    dialog --infobox "AGUARDE..." 5 40
    echo -ne "\033[1;33mAGUARDE \033[1;37m- \033[1;33m["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[1;31m#"
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[1;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "\033[1;33mAGUARDE \033[1;37m- \033[1;33m["
    done
    echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
    tput cnorm
}

clear

fun_chuser() {
    while true; do
        resposta=$(dialog --menu "GERENCIAR CHECKUSER" 15 40 7 \
            1 "ATIVAR CHECKUSER" \
            2 "DESINSTALAR CHECKUSER" \
            0 "VOLTAR" 3>&1 1>&2 2>&3)
        case $resposta in
            1)
                if ps x | grep -w atx.py | grep -v grep 1>/dev/null 2>/dev/null; then
                    clear
                    dialog --infobox "DESATIVANDO O CHECKUSER" 5 40
                    fun_socksoff() {
                        for pidcheckuser in $(screen -ls | grep ".checkuser" | awk {'print $1'}); do
                            screen -r -S "$pidcheckuser" -X quit
                        done
                        [[ $(grep -wc "atx.py" /etc/autostart) != '0' ]] && {
                            sed -i '/atx.py/d' /etc/autostart
                        }
                        sleep 1
                        screen -wipe >/dev/null
                    }
                    fun_bar 'fun_socksoff'
                    dialog --infobox "CHECKUSER DESATIVADO COM SUCESSO!" 5 40
                    sleep 3
                else
                    clear
                    dominio=$(dialog --inputbox "QUAL DOMÍNIO DESEJA UTILIZAR?" 8 40 3>&1 1>&2 2>&3)
                    if [ -z "$dominio" ]; then
                        dialog --msgbox "Domínio inválido!" 7 40
                        sleep 3
                        fun_chuser
                    fi
                    porta=$(dialog --inputbox "QUAL PORTA DESEJA UTILIZAR?" 8 40 3>&1 1>&2 2>&3)
                    if [ -z "$porta" ]; then
                        dialog --msgbox "Porta inválida!" 7 40
                        sleep 3
                        fun_chuser
                    fi
                    link="http://$dominio:$porta/checkUser"
                    verif_ptrs $porta
                    fun_inisocks() {
                        sleep 1
                        screen -dmS checkuser python3 /usr/lib/atx/atx.py $porta
                        if [ $(grep -wc "atx" /etc/autostart) = '0' ]; then
                            echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'atx' -X quit;  screen -dmS checkuser python3 /usr/lib/checkuser/atx.py $porta; }" >>/etc/autostart
                        else
                            sed -i '/atx/d' /etc/autostart
                            echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'atx' -X quit;  screen -dmS checkuser python3 /usr/lib/checkuser/atx.py $porta; }" >>/etc/autostart
                        fi
                    }
                    dialog --infobox "INICIANDO O CHECKUSER" 5 40
                    fun_bar 'fun_inisocks'
                    dialog --infobox "CHECKUSER ATIVADO COM SUCESSO\n\nLink: $link\n\nAguarde um momento, a porta pode demorar para subir." 10 60
                    sleep 3
                fi
                ;;
            2)
                dialog --infobox "Desinstalando o Checkuser..." 5 40
                uninstall_checkuser
                ;;
            0)
                dialog --infobox "Saindo..." 5 40
                sleep 1
                clear
                exit
                ;;
            *)
                dialog --msgbox "Opção inválida!" 7 40
                sleep 1
                ;;
        esac
    done
}

fun_chuser
